### ISSUE TITLE
九月为什么要最后一个选座位

### ISSUE THREAD

**Issue by yujiajian** [yidingcn/novel#6]
原文：
九月是全年级第一名，照理说可以先选座位，可是她心里却并不开心。
“完了，我第一个选座位，岂不是没有主动权了?就算选了一个好座位，万一来个猪头三坐我旁边怎么办？”
很多时候，好的同桌比好的座位跟重要。
下午。
“韩九月同学，你可以第一个选座位了。”
“老师，我想最后一个选！”

最后一个选，不就没得选了吗？
我认为到底第几个选最佳，应该好好研究下。。。。

**Comment by yujiajian** [comment]
。。。

**Comment by karataliu** [comment]
嗯 。。这可以成为后来的面试题。
